# Generated by Django 4.0.2 on 2022-02-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newuser",
            name="token",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
